-- ═══════════════════════════════════════════════════════════════════
-- HYDROCALC — SCHÉMA SUPABASE
-- ═══════════════════════════════════════════════════════════════════
--
-- IMPORTANT — CE FICHIER N'EST PLUS UN SCRIPT D'INSTALLATION.
--
-- L'ancien snapshot `schema.sql` prédatait le durcissement de production et
-- contenait notamment des policies RLS trop permissives sur `profiles` et
-- `usage_quotas`. Le conserver comme script exécutable risquerait de recréer
-- une base vulnérable lors d'un nouveau déploiement.
--
-- SOURCE DE VÉRITÉ : `supabase/migrations/`, appliquée dans l'ordre documenté
-- dans `docs/DEPLOYMENT_SECURITY.md` après exécution du preflight.
--
-- Ordre de la baseline de sécurité actuelle :
--
--   1. 20260831_security_hardening.sql
--   2. 20260831_auth_entitlements.sql
--   3. 20260831_trial_security.sql
--   4. 20260901_server_quotas.sql
--   5. 20260902_messaging_security.sql
--   6. 202609021900_messaging_followup.sql
--   7. 202609022030_messaging_blocking_reports.sql
--   8. 20260902_forum_foundation.sql
--   9. 202609022200_community_moderation_search.sql
--
-- Les Edge Functions de `supabase/functions/` doivent ensuite être déployées
-- conformément au même runbook.
--
-- Ne copiez pas ici un nouveau snapshot manuel. Si un schéma consolidé devient
-- nécessaire, il devra être GÉNÉRÉ à partir d'une base ayant reçu toutes les
-- migrations, puis vérifié par CI afin de ne jamais diverger des policies RLS.
--
-- Ce fichier reste volontairement composé uniquement de commentaires :
-- l'exécuter ne crée, ne modifie et ne supprime aucun objet de base de données.
-- ═══════════════════════════════════════════════════════════════════
