-- HydroCalc — file de moderation, sanctions administrateur et journal d'audit.
-- Les signalements restent la seule porte d'entree vers le contenu prive modere.

alter table public.message_reports
  add column if not exists admin_note text,
  add column if not exists decision text,
  add column if not exists reviewed_by uuid references public.profiles(id) on delete set null;

alter table public.message_reports drop constraint if exists message_reports_decision_check;
alter table public.message_reports add constraint message_reports_decision_check
  check (decision is null or decision in ('no_action','warning','suspend','ban'));

create table if not exists public.moderation_sanctions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  report_id uuid references public.message_reports(id) on delete set null,
  action text not null check (action in ('warning','suspend','ban')),
  reason text not null check (char_length(reason) between 3 and 1000),
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  active boolean not null default true,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  constraint moderation_suspension_end check (action <> 'suspend' or ends_at is not null)
);
create index if not exists moderation_sanctions_user_active_idx on public.moderation_sanctions(user_id,active,created_at desc);

create table if not exists public.moderation_audit_log (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references public.profiles(id),
  report_id uuid references public.message_reports(id) on delete set null,
  target_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  note text,
  created_at timestamptz not null default now()
);
create index if not exists moderation_audit_created_idx on public.moderation_audit_log(created_at desc);

alter table public.moderation_sanctions enable row level security;
alter table public.moderation_audit_log enable row level security;

revoke all on public.moderation_sanctions, public.moderation_audit_log from anon;
revoke insert, update, delete on public.moderation_sanctions, public.moderation_audit_log from authenticated;
grant select on public.moderation_sanctions, public.moderation_audit_log to authenticated;

drop policy if exists "moderation sanctions admin read" on public.moderation_sanctions;
create policy "moderation sanctions admin read" on public.moderation_sanctions
for select to authenticated using (
  exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin=true)
);

drop policy if exists "moderation audit admin read" on public.moderation_audit_log;
create policy "moderation audit admin read" on public.moderation_audit_log
for select to authenticated using (
  exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin=true)
);

-- Nombre de dossiers en attente : utilisable pour le badge administrateur.
create or replace function public.moderation_pending_count()
returns bigint language sql stable security definer set search_path=public as $$
  select case when exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin=true)
    then (select count(*) from public.message_reports r where r.status='pending')
    else 0 end;
$$;
revoke all on function public.moderation_pending_count() from public;
grant execute on function public.moderation_pending_count() to authenticated;

-- Lecture admin strictement liee au message signale, sans navigateur de conversations privees.
create or replace function public.moderation_get_report(p_report_id uuid)
returns table(
  report_id uuid, report_status text, report_reason text, reported_at timestamptz,
  message_id uuid, message_content text, message_created_at timestamptz,
  reported_user_id uuid, reported_user_name text, reporter_id uuid
)
language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin=true) then
    raise exception 'admin required';
  end if;
  return query
  select r.id,r.status,r.reason,r.created_at,m.id,m.contenu,m.created_at,
         m.sender_id,m.sender_name,r.reporter_id
  from public.message_reports r
  join public.messages m on m.id=r.message_id
  where r.id=p_report_id;
end;
$$;
revoke all on function public.moderation_get_report(uuid) from public;
grant execute on function public.moderation_get_report(uuid) to authenticated;

create or replace function public.moderation_decide_report(
  p_report_id uuid,
  p_decision text,
  p_note text default null,
  p_suspend_until timestamptz default null
) returns boolean
language plpgsql security definer set search_path=public as $$
declare
  v_admin uuid:=auth.uid();
  v_target uuid;
  v_note text:=nullif(trim(coalesce(p_note,'')),'');
begin
  if not exists(select 1 from public.profiles p where p.id=v_admin and p.is_admin=true) then raise exception 'admin required'; end if;
  if p_decision not in ('no_action','warning','suspend','ban') then raise exception 'invalid decision'; end if;
  if v_note is not null and char_length(v_note)>2000 then raise exception 'note too long'; end if;

  select m.sender_id into v_target
  from public.message_reports r join public.messages m on m.id=r.message_id
  where r.id=p_report_id for update of r;
  if v_target is null then raise exception 'report not found'; end if;
  if p_decision='suspend' and (p_suspend_until is null or p_suspend_until<=now()) then raise exception 'invalid suspension end'; end if;

  update public.message_reports
  set status='reviewed', reviewed_at=now(), reviewed_by=v_admin,
      decision=p_decision, admin_note=v_note
  where id=p_report_id;

  if p_decision in ('warning','suspend','ban') then
    insert into public.moderation_sanctions(user_id,report_id,action,reason,ends_at,created_by)
    values(v_target,p_report_id,p_decision,coalesce(v_note,'Decision de moderation HydroCalc'),
           case when p_decision='suspend' then p_suspend_until else null end,v_admin);
  end if;

  insert into public.moderation_audit_log(admin_id,report_id,target_user_id,action,note)
  values(v_admin,p_report_id,v_target,p_decision,v_note);
  return true;
end;
$$;
revoke all on function public.moderation_decide_report(uuid,text,text,timestamptz) from public;
grant execute on function public.moderation_decide_report(uuid,text,text,timestamptz) to authenticated;

-- Les suspensions/bannissements actifs bloquent la messagerie. L'avertissement reste informatif.
create or replace function public.messaging_user_sanctioned(p_uid uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from public.moderation_sanctions s
    where s.user_id=p_uid and s.active=true
      and (s.action='ban' or (s.action='suspend' and s.ends_at>now()))
  );
$$;
revoke all on function public.messaging_user_sanctioned(uuid) from public;
grant execute on function public.messaging_user_sanctioned(uuid) to authenticated;
